<?php
namespace UWA\Admin;
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

class Admin
{
    public static function register()
    {
        add_action('admin_menu', [self::class, 'register_admin_menu']);
        add_action('admin_enqueue_scripts', [self::class, 'enqueue_admin_scripts']);
    }
    public static function register_admin_menu()
    {
        add_menu_page(
            __('Ultimate Woo Addons', 'ultimate-woo-addons'),
            __('Ultimate Woo Addons', 'ultimate-woo-addons'),
            'manage_options',
            'ultimate-woo-addons',
            [self::class, 'render_admin_app'],
            'dashicons-admin-generic'
        );
    }

    public static function render_admin_app()
    {
        echo '<div id="ultimate-woo-addons-admin"></div>';
        wp_enqueue_script('ultimate-woo-addons-admin');
    }

    public static function enqueue_admin_scripts($hook)
    {
        if ($hook !== 'toplevel_page_ultimate-woo-addons') {
            return;
        }
        //index.asset.php file generated by webpack
        $asset_file = include UWA_PATH . '/build/admin/index.asset.php';

        wp_enqueue_script(
            'ultimate-woo-addons-admin',
            UWA_URL . '/build/admin/index.js',
            $asset_file['dependencies'],
            $asset_file['version'],
            true
        );
        
    }
}